version: "3"
services:
  web:
    build: .
    image: toptasc/books_db:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - m6a
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: m6a-Password
       MYSQL_DATABASE: m6abooks
       MYSQL_USER: m6a
       MYSQL_PASSWORD: M6A-password
    networks:
      - m6a
networks:
  m6a:
    driver: bridge